# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create deploy pages directory and copy existing src files over
        run: |
          mkdir pages 
          cp -r src/* pages/
          ls -sail pages/ 

      - name: Auto Minify
        uses: nizarmah/auto-minify@v3
        with:
          directory: 'src/css'
          output: 'pages/css'

      - name: Rename minified css
        run: |
          ls -sail pages/
          sudo mv pages/css/main.min.css pages/css/main.css

      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: pages
          base-url-path: https://jessey.bullock.sh/ 

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          # Upload entire repository
          path: 'pages'

      - name: Output stats
        run: |
          echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}" 
          echo "pages-url = ${{ steps.deployment.outputs.page_url }}"
          ls -sail pages/ 


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4    

      - name: Submit sitemap
        run: |
          curl https://www.google.com/ping?sitemap=https://jessey.bullock.sh/sitemap.xml  
          
          
